baseURL = "https://sitemana.netlify.app"
languageCode = "it-IT"
summaryLength = "10"
theme = "Sitemana-theme"
title = "Sitemana"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "125/A, CA Commercial Area, California, USA"
author = "Antonio Trento"
copyright = "Copyright &copy; 2020 a theme by [SiteMana](https://https://sitemana.netlify.app/)"
description = "Sitemana contatti e specifiche"
email = "sitemana@email.com"
google_analytics_id = ""
home = "Home"
logo = "images/logo.png"
phone = "+880 2544 658 256"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = "/images/preloader.gif"
[[params.social]]
URL = "https://facebook.com/lantoniotrento"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
